-- MySQL Script generated by MySQL Workbench
-- Mon Sep 13 14:02:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company_type` (
  `companyTypeId` INT NOT NULL AUTO_INCREMENT,
  `companyTypeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`companyTypeId`),
  UNIQUE INDEX `companyTypeName_UNIQUE` (`companyTypeName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `companyId` INT NOT NULL AUTO_INCREMENT,
  `companyTypeId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `StockPrice` INT NOT NULL,
  `risk` VARCHAR(45) NOT NULL,
  `stockTotal` INT NOT NULL,
  PRIMARY KEY (`companyId`),
  CONSTRAINT `fk_company_Type_Id`
    FOREIGN KEY (`companyId`)
    REFERENCES `mydb`.`company_type` (`companyTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leaderboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leaderboard` (
  `rankId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `score` INT NOT NULL,
  PRIMARY KEY (`rankId`),
  INDEX `fk_user_id_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`users` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bullMarket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bullMarket` (
  `roll` INT NOT NULL,
  `mod` INT NOT NULL,
  `companyId` INT NOT NULL,
  UNIQUE INDEX `roll_UNIQUE` (`roll` ASC) VISIBLE,
  UNIQUE INDEX `companyId_UNIQUE` (`companyId` ASC) VISIBLE,
  CONSTRAINT `fk_company_id`
    FOREIGN KEY (`companyId`)
    REFERENCES `mydb`.`company` (`companyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bearMarket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bearMarket` (
  `roll` INT NOT NULL,
  `mod` INT NOT NULL,
  `companyId` INT NOT NULL,
  UNIQUE INDEX `roll_UNIQUE` (`roll` ASC) VISIBLE,
  INDEX `fk_company_id_idx` (`companyId` ASC) VISIBLE,
  CONSTRAINT `fk_company_id`
    FOREIGN KEY (`companyId`)
    REFERENCES `mydb`.`company` (`companyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
