    
-- INSERT DATA
-- COMPANY TYPES
    INSERT INTO `hedge`.`company_type` (`company_type_name`) VALUES ('Cultural');
	INSERT INTO `hedge`.`company_type` (`company_type_name`) VALUES ('Hybrid');
	INSERT INTO `hedge`.`company_type` (`company_type_name`) VALUES ('Industrial');
	INSERT INTO `hedge`.`company_type` (`company_type_name`) VALUES ('Natural Res.');
    INSERT INTO `hedge`.`company_type` (`company_type_name`) VALUES ('Tech');
    
    -- COMPANIES
    -- CULTURAL
    INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('1', 'Academiic', '25', 'High', '100', '40');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('1', 'Health Harbor', '25', 'High', '100', '35');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('1', 'Leisure Machine', '25', 'Medium', '100', '30');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('1', 'Social Cells', '25', 'Medium', '100', '20');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('1', 'UX Gallery', '25', 'High', '100', '35');
	-- HYBRID
    INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('2', 'Bright Miner', '25', 'Low', '100', '20');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('2', 'Digitalic', '25', 'High', '100', '35');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('2', 'Earthzy', '25', 'Low', '100', '20');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('2', 'EcoAlley', '25', 'Medium', '100', '20');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('2', 'Modaxy', '25', 'High', '100', '40');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('2', 'Tourux', '25', 'High', '100', '35');
	-- INDUSTRIAL
    INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('3', 'Cargo Ace', '25', 'High', '100', '45');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('3', 'PowerLy', '25', 'Low', '100', '15');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('3', 'Rival Industry', '25', 'Medium', '100', '30');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('3', 'Supply Phase', '25', 'High', '100', '45');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('3', 'Ultra Foundry', '25', 'Low', '100', '15');
	-- NATURAL RES.
    INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('4', 'Agribuilder', '25', 'Medium', '100', '30');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('4', 'Coal Stove', '25', 'Low', '100', '15');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('4', 'PetroYield', '25', 'Low', '100', '10');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('4', 'Prosperity Fuel', '25', 'Medium', '100', '30');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('4', 'TimberFly', '25', 'Low', '100', '10');
	-- TECH
    INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('5', 'Cammunition', '25', 'Medium', '100', '20');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('5', 'Grandlytics', '25', 'Medium', '100', '25');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('5', 'Pharmanetic', '25', 'Medium', '100', '30');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('5', 'Protectice', '25', 'Medium', '100', '20');
	INSERT INTO `hedge`.`company` (`company_type_id`, `name`, `stock_price`, `risk`, `stock_total`, `dividend`) VALUES ('5', 'Simply Sentient', '25', 'Medium', '100', '25');

	-- MARKET TYPE
	-- Academiic - ID:1
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (1,1,1,-9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (2,2,1,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (3,3,1,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (4,4,1,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (5,5,1,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (6,6,1,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (7,7,1,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (8,8,1,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (9,9,1,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (10,10,1,13,-13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (11,11,1,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (12,12,1,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (13,13,1,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (14,14,1,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (15,15,1,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (16,16,1,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (17,17,1,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (18,18,1,-13,13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (19,19,1,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (20,20,1,-26,26);
	-- Health Harbor - ID:2
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (21,1,2,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (22,2,2,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (23,3,2,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (24,4,2,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (25,5,2,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (26,6,2,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (27,7,2,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (28,8,2,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (29,9,2,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (30,10,2,13,-13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (31,11,2,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (32,12,2,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (33,13,2,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (34,14,2,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (35,15,2,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (36,16,2,-12,12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (37,17,2,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (38,18,2,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (39,19,2,14,-14);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (40,20,2,26,-26);
    -- Leisure Machine ID:3
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (41,1,3,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (42,2,3,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (43,3,3,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (44,4,3,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (45,5,3,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (46,6,3,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (47,7,3,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (48,8,3,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (49,9,3,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (50,10,3,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (51,11,3,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (52,12,3,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (53,13,3,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (54,14,3,-15,15);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (55,15,3,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (56,16,3,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (57,17,3,-11,11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (58,18,3,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (59,19,3,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (60,20,3,-20,20);
    -- Social Cells ID:4
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (61,1,4,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (62,2,4,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (63,3,4,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (64,4,4,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (65,5,4,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (66,6,4,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (67,7,4,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (68,8,4,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (69,9,4,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (70,10,4,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (71,11,4,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (72,12,4,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (73,13,4,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (74,14,4,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (75,15,4,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (76,16,4,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (77,17,4,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (78,18,4,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (79,19,4,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (80,20,4,19,-19);
    -- UX Gallery ID:5
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (81,1,5,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (82,2,5,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (83,3,5,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (84,4,5,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (85,5,5,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (86,6,5,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (87,7,5,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (88,8,5,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (89,9,5,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (90,10,5,13,-13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (91,11,5,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (92,12,5,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (93,13,5,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (94,14,5,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (95,15,5,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (96,16,5,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (97,17,5,13,-13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (98,18,5,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (99,19,5,-13,13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (100,20,5,22,-22);
	-- Bright Miner ID:6
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (101,1,6,2,-2);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (102,2,6,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (103,3,6,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (104,4,6,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (105,5,6,4,-4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (106,6,6,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (107,7,6,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (108,8,6,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (109,9,6,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (110,10,6,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (111,11,6,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (112,12,6,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (113,13,6,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (114,14,6,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (115,15,6,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (116,16,6,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (117,17,6,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (118,18,6,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (119,19,6,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (120,20,6,12,-12);
    -- Digitalic ID:7
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (121,1,7,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (122,2,7,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (123,3,7,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (124,4,7,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (125,5,7,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (126,6,7,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (127,7,7,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (128,8,7,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (129,9,7,-11,11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (130,10,7,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (131,11,7,-12,12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (132,12,7,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (133,13,7,-12,12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (134,14,7,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (135,15,7,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (136,16,7,-14,14);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (137,17,7,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (138,18,7,13,-13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (139,19,7,-13,13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (140,20,7,-24,24);
    -- Earthzy ID:8
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (141,1,8,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (142,2,8,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (143,3,8,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (144,4,8,4,-4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (145,5,8,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (146,6,8,-3,3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (147,7,8,-3,3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (148,8,8,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (149,9,8,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (150,10,8,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (151,11,8,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (152,12,8,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (153,13,8,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (154,14,8,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (155,15,8,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (156,16,8,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (157,17,8,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (158,18,8,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (159,19,8,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (160,20,8,14,-14);
	-- EcoAlley ID:9
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (161,1,9,4,-4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (162,2,9,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (163,3,9,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (164,4,9,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (165,5,9,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (166,6,9,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (167,7,9,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (168,8,9,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (169,9,9,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (170,10,9,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (171,11,9,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (172,12,9,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (173,13,9,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (174,14,9,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (175,15,9,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (176,16,9,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (177,17,9,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (178,18,9,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (179,19,9,-13,13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (180,20,9,15,-15);
    -- Modaxy ID:10
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (181,1,10,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (182,2,10,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (183,3,10,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (184,4,10,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (185,5,10,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (186,6,10,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (187,7,10,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (188,8,10,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (189,9,10,-13,13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (190,10,10,14,-14);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (191,11,10,13,-13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (192,12,10,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (193,13,10,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (194,14,10,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (195,15,10,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (196,16,10,-14,14);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (197,17,10,16,-16);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (198,18,10,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (199,19,10,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (200,20,10,29,-29);
    -- Tourux ID:11
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (201,1,11,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (202,2,11,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (203,3,11,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (204,4,11,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (205,5,11,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (206,6,11,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (207,7,11,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (208,8,11,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (209,9,11,13,-13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (210,10,11,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (211,11,11,-11,11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (212,12,11,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (213,13,11,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (214,14,11,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (215,15,11,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (216,16,11,13,-13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (217,17,11,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (218,18,11,-14,14);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (219,19,11,13,-13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (220,20,11,21,-21);   
    -- Cargo Acer ID:12
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (221,1,12,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (222,2,12,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (223,3,12,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (224,4,12,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (225,5,12,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (226,6,12,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (227,7,12,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (228,8,12,-11,11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (229,9,12,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (230,10,12,14,-14);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (231,11,12,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (232,12,12,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (233,13,12,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (234,14,12,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (235,15,12,-11,11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (236,16,12,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (237,17,12,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (238,18,12,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (239,19,12,-11,11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (240,20,12,-33,33);
    -- PowerLy ID:13
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (241,1,13,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (242,2,13,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (243,3,13,4,-4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (244,4,13,-3,3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (245,5,13,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (246,6,13,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (247,7,13,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (248,8,13,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (249,9,13,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (250,10,13,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (251,11,13,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (252,12,13,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (253,13,13,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (254,14,13,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (255,15,13,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (256,16,13,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (257,17,13,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (258,18,13,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (259,19,13,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (260,20,13,12,-12);
    -- Rival Industry ID:14
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (261,1,14,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (262,2,14,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (263,3,14,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (264,4,14,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (265,5,14,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (266,6,14,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (267,7,14,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (268,8,14,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (269,9,14,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (270,10,14,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (271,11,14,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (272,12,14,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (273,13,14,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (274,14,14,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (275,15,14,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (276,16,14,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (277,17,14,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (278,18,14,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (279,19,14,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (280,20,14,17,-17);
    -- Supply Phase ID:15
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (281,1,15,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (282,2,15,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (283,3,15,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (284,4,15,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (285,5,15,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (286,6,15,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (287,7,15,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (288,8,15,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (289,9,15,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (290,10,15,14,-14);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (291,11,15,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (292,12,15,-11,11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (293,13,15,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (294,14,15,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (295,15,15,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (296,16,15,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (297,17,15,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (298,18,15,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (299,19,15,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (300,20,15,-32,32);
    -- Ultra Foundry ID:16
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (301,1,16,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (302,2,16,2,-2);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (303,3,16,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (304,4,16,4,-4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (305,5,16,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (306,6,16,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (307,7,16,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (308,8,16,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (309,9,16,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (310,10,16,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (311,11,16,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (312,12,16,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (313,13,16,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (314,14,16,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (315,15,16,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (316,16,16,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (317,17,16,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (318,18,16,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (319,19,16,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (320,20,16,11,-11);
	-- Agribuilder ID:17
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (321,1,17,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (322,2,17,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (323,3,17,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (324,4,17,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (325,5,17,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (326,6,17,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (327,7,17,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (328,8,17,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (329,9,17,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (330,10,17,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (331,11,17,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (332,12,17,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (333,13,17,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (334,14,17,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (335,15,17,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (336,16,17,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (337,17,17,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (338,18,17,-11,11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (339,19,17,-14,14);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (340,20,17,-19,19);
    -- Coal State ID:18
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (341,1,18,2,-2);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (342,2,18,4,-4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (343,3,18,2,-2);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (344,4,18,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (345,5,18,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (346,6,18,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (347,7,18,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (348,8,18,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (349,9,18,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (350,10,18,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (351,11,18,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (352,12,18,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (353,13,18,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (354,14,18,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (355,15,18,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (356,16,18,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (357,17,18,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (358,18,18,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (359,19,18,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (360,20,18,11,-11);
    -- PetroYield ID:19
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (361,1,19,1,-1);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (362,2,19,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (363,3,19,4,-4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (364,4,19,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (365,5,19,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (366,6,19,-3,3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (367,7,19,-3,3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (368,8,19,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (369,9,19,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (370,10,19,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (371,11,19,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (372,12,19,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (373,13,19,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (374,14,19,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (375,15,19,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (376,16,19,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (377,17,19,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (378,18,19,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (379,19,19,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (380,20,19,10,-10);
    -- Prosperity Fuel ID:20
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (381,1,20,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (382,2,20,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (383,3,20,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (384,4,20,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (385,5,20,4,-4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (386,6,20,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (387,7,20,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (388,8,20,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (389,9,20,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (390,10,20,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (391,11,20,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (392,12,20,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (393,13,20,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (394,14,20,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (395,15,20,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (396,16,20,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (397,17,20,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (398,18,20,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (399,19,20,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (400,20,20,18,-18);
    -- TimberFly ID:21
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (401,1,21,2,-2);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (402,2,21,2,-2);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (403,3,21,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (404,4,21,2,-2);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (405,5,21,3,-3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (406,6,21,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (407,7,21,-3,3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (408,8,21,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (409,9,21,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (410,10,21,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (411,11,21,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (412,12,21,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (413,13,21,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (414,14,21,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (415,15,21,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (416,16,21,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (417,17,21,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (418,18,21,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (419,19,21,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (420,20,21,10,-10);
    -- Cammunition ID:22
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (421,1,22,-3,3);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (422,2,22,4,-4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (423,3,22,4,-4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (424,4,22,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (425,5,22,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (426,6,22,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (427,7,22,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (428,8,22,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (429,9,22,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (430,10,22,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (431,11,22,8,-8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (432,12,22,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (433,13,22,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (434,14,22,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (435,15,22,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (436,16,22,-11,11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (437,17,22,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (438,18,22,-13,13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (439,19,22,-12,12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (440,20,22,-17,17);
    -- Grandlytics ID:23
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (441,1,23,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (442,2,23,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (443,3,23,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (444,4,23,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (445,5,23,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (446,6,23,4,-4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (447,7,23,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (448,8,23,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (449,9,23,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (450,10,23,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (451,11,23,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (452,12,23,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (453,13,23,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (454,14,23,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (455,15,23,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (456,16,23,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (457,17,23,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (458,18,23,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (459,19,23,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (460,20,23,20,-20);
    -- Pharmanetic ID:24
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (461,1,24,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (462,2,24,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (463,3,24,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (464,4,24,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (465,5,24,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (466,6,24,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (467,7,24,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (468,8,24,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (469,9,24,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (470,10,24,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (471,11,24,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (472,12,24,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (473,13,24,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (474,14,24,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (475,15,24,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (476,16,24,-13,13);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (477,17,24,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (478,18,24,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (479,19,24,-12,12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (480,20,24,-20,20);
    -- Protectice ID:25
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (481,1,25,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (482,2,25,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (483,3,25,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (484,4,25,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (485,5,25,-4,4);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (486,6,25,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (487,7,25,-5,5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (488,8,25,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (489,9,25,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (490,10,25,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (491,11,25,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (492,12,25,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (493,13,25,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (494,14,25,11,-11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (495,15,25,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (496,16,25,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (497,17,25,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (498,18,25,12,-12);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (499,19,25,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (500,20,25,17,-17);
    -- Simply Sentient ID:26
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (501,1,26,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (502,2,26,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (503,3,26,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (504,4,26,5,-5);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (505,5,26,-7,7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (506,6,26,6,-6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (507,7,26,-6,6);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (508,8,26,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (509,9,26,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (510,10,26,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (511,11,26,-8,8);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (512,12,26,7,-7);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (513,13,26,9,-9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (514,14,26,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (515,15,26,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (516,16,26,10,-10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (517,17,26,-10,10);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (518,18,26,-9,9);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (519,19,26,-11,11);
	INSERT INTO `hedge`.`market_type` (`market_id`,`roll`,`company_id`,`bull_modify`,`bear_modify`) VALUES (520,20,26,-19,19);
    
delimiter //
create procedure set_known_good_state()
begin
	delete from leaderboard;
    delete from market;
    alter table market auto_increment = 1;
    delete from game;
    alter table game auto_increment = 1;
    
	-- Create game
	INSERT INTO `hedge`.`game` (`user_id`, `year_number`) VALUES ('1', '1');
   
	-- Create market
	INSERT INTO `hedge`.`market` (`company_id`, `price`, `year_num`, `game_id`, `stock_purchased`, `long`) VALUES ('1', '25', '1', '1', '0', '1');
	INSERT INTO `hedge`.`market` (`company_id`, `price`, `year_num`, `game_id`, `stock_purchased`, `long`) VALUES ('2', '25', '1', '1', '0', '1');

	-- Add to leaderboard 
    INSERT INTO `hedge`.`leaderboard` (`user_name`, `score`) VALUES ('user1', '250');
end //
-- 4. Change the statement terminator back to the original.
delimiter ;